baseURL = 'https://localhost:1313/'
defaultContentLanguage = "es"
languageCode = "es-ES"
title = 'Chinestesia'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  custom_css = ["css/custom.css"]